/*
*    Proyecto de Laboratorio 1 (Sección 1)
*     Integrantes:
*     Canelon Valmore CI: 22270191
*     Cohen Kevin  CI: 20670359
*     Jiménez Jaimary CI: 22263583
*     Lugo Brisleidy CI: 22181168
*     Serrano Joselyn CI: 22271356
*/
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JMenuItem;


public class VMenuPrin extends javax.swing.JFrame {

    /**
     * Creates new form VMenuPrin
     */
    public VMenuPrin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelimag = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuproyectos = new javax.swing.JMenu();
        jMenuItemgestproyectos = new javax.swing.JMenuItem();
        jMenuItemgestclientes = new javax.swing.JMenuItem();
        jMenuItemAsigCand = new javax.swing.JMenuItem();
        jMenuItemIngreso = new javax.swing.JMenuItem();
        jMenucandidato = new javax.swing.JMenu();
        jMenuItemgestcandidato = new javax.swing.JMenuItem();
        jMenuItemgestentrevistas = new javax.swing.JMenuItem();
        jMenuempleados = new javax.swing.JMenu();
        jMenuItemregnomina = new javax.swing.JMenuItem();
        jMenuItemregfaltas = new javax.swing.JMenuItem();
        jMenuferiado = new javax.swing.JMenu();
        jMenuItemferiado = new javax.swing.JMenuItem();
        jMenuconsultas = new javax.swing.JMenu();
        jMenuItemconsentrevistas = new javax.swing.JMenuItem();
        jMenuItemconsrecord = new javax.swing.JMenuItem();
        jMenuItemconsutilidad = new javax.swing.JMenuItem();
        jMenuItemconshorastrab = new javax.swing.JMenuItem();
        jMenuItemconscandidatos = new javax.swing.JMenuItem();
        jMenuItemconsfaltas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelimag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/desarrollo.png"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(35, 202, 204));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 255));

        jMenuproyectos.setForeground(new java.awt.Color(255, 255, 255));
        jMenuproyectos.setText("Proyectos");
        jMenuproyectos.setAlignmentX(2.0F);
        jMenuproyectos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuproyectos.setMargin(new java.awt.Insets(5, 10, 5, 5));

        jMenuItemgestproyectos.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemgestproyectos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemgestproyectos.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemgestproyectos.setText("Gestionar proyectos");
        jMenuproyectos.add(jMenuItemgestproyectos);

        jMenuItemgestclientes.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemgestclientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemgestclientes.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemgestclientes.setText("Gestionar clientes");
        jMenuproyectos.add(jMenuItemgestclientes);

        jMenuItemAsigCand.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemAsigCand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemAsigCand.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemAsigCand.setText("Asignar Candidatos");
        jMenuproyectos.add(jMenuItemAsigCand);

        jMenuItemIngreso.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemIngreso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemIngreso.setText("Registrar Ingreso");
        jMenuproyectos.add(jMenuItemIngreso);

        jMenuBar1.add(jMenuproyectos);

        jMenucandidato.setForeground(new java.awt.Color(255, 255, 255));
        jMenucandidato.setText("Candidatos");
        jMenucandidato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenucandidato.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItemgestcandidato.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemgestcandidato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemgestcandidato.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemgestcandidato.setText("Gestionar candidatos");
        jMenucandidato.add(jMenuItemgestcandidato);

        jMenuItemgestentrevistas.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemgestentrevistas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemgestentrevistas.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemgestentrevistas.setText("Registrar entrevistas");
        jMenuItemgestentrevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemgestentrevistasActionPerformed(evt);
            }
        });
        jMenucandidato.add(jMenuItemgestentrevistas);

        jMenuBar1.add(jMenucandidato);

        jMenuempleados.setForeground(new java.awt.Color(255, 255, 255));
        jMenuempleados.setText("Empleados");
        jMenuempleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuempleados.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItemregnomina.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemregnomina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemregnomina.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemregnomina.setText("Registrar nomina");
        jMenuempleados.add(jMenuItemregnomina);

        jMenuItemregfaltas.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemregfaltas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemregfaltas.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemregfaltas.setText("Registrar faltas ");
        jMenuempleados.add(jMenuItemregfaltas);

        jMenuBar1.add(jMenuempleados);

        jMenuferiado.setForeground(new java.awt.Color(255, 255, 255));
        jMenuferiado.setText("Fechas Feriadas");
        jMenuferiado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuferiado.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItemferiado.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemferiado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemferiado.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemferiado.setText("Gestionar fechas");
        jMenuferiado.add(jMenuItemferiado);

        jMenuBar1.add(jMenuferiado);

        jMenuconsultas.setForeground(new java.awt.Color(255, 255, 255));
        jMenuconsultas.setText("Consultas");
        jMenuconsultas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuconsultas.setMargin(new java.awt.Insets(5, 5, 5, 5));

        jMenuItemconsentrevistas.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemconsentrevistas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemconsentrevistas.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemconsentrevistas.setText("Entrevistas");
        jMenuItemconsentrevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemconsentrevistasActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemconsentrevistas);

        jMenuItemconsrecord.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemconsrecord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemconsrecord.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemconsrecord.setText("Record de pago");
        jMenuItemconsrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemconsrecordActionPerformed(evt);
            }
        });
        jMenuconsultas.add(jMenuItemconsrecord);

        jMenuItemconsutilidad.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemconsutilidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemconsutilidad.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemconsutilidad.setText("Utilidad Obtenida");
        jMenuconsultas.add(jMenuItemconsutilidad);

        jMenuItemconshorastrab.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemconshorastrab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemconshorastrab.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemconshorastrab.setText("Horas trabajadas ");
        jMenuconsultas.add(jMenuItemconshorastrab);

        jMenuItemconscandidatos.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemconscandidatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemconscandidatos.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemconscandidatos.setText("Candidatos");
        jMenuconsultas.add(jMenuItemconscandidatos);

        jMenuItemconsfaltas.setBackground(new java.awt.Color(35, 202, 204));
        jMenuItemconsfaltas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItemconsfaltas.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemconsfaltas.setText("Faltas de empleados");
        jMenuconsultas.add(jMenuItemconsfaltas);

        jMenuBar1.add(jMenuconsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelimag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelimag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 667));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemconsentrevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemconsentrevistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemconsentrevistasActionPerformed

    private void jMenuItemconsrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemconsrecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemconsrecordActionPerformed

    private void jMenuItemgestentrevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemgestentrevistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemgestentrevistasActionPerformed

    public JMenuItem getjMenuItemconscandidatos() {
        return jMenuItemconscandidatos;
    }

    public JMenuItem getjMenuItemIngreso() {
        return jMenuItemIngreso;
    }

    public JMenuItem getjMenuItemconsentrevistas() {
        return jMenuItemconsentrevistas;
    }

    public JMenuItem getjMenuItemconsfaltas() {
        return jMenuItemconsfaltas;
    }

    public JMenuItem getjMenuItemconshorastrab() {
        return jMenuItemconshorastrab;
    }

    public JMenuItem getjMenuItemconsrecord() {
        return jMenuItemconsrecord;
    }

    public JMenuItem getjMenuItemconsutilidad() {
        return jMenuItemconsutilidad;
    }

    public JMenuItem getjMenuItemferiado() {
        return jMenuItemferiado;
    }

    public JMenuItem getjMenuItemregfaltas() {
        return jMenuItemregfaltas;
    }

    public JMenuItem getjMenuItemgestcandidato() {
        return jMenuItemgestcandidato;
    }

    public JMenuItem getjMenuItemgestclientes() {
        return jMenuItemgestclientes;
    }

    public JMenuItem getjMenuItemgestentrevistas() {
        return jMenuItemgestentrevistas;
    }

    public JMenuItem getjMenuItemgestproyectos() {
        return jMenuItemgestproyectos;
    }

    public JMenuItem getjMenuItemregnomina() {
        return jMenuItemregnomina;
    }

    public JMenuItem getjMenuItemAsigCand() {
        return jMenuItemAsigCand;
    }
    
    public void agregarListener(ActionListener accion){
        
        this.jMenuItemconscandidatos.addActionListener(accion);
        this.jMenuItemconsentrevistas.addActionListener(accion);
        this.jMenuItemconsfaltas.addActionListener(accion);
        this.jMenuItemconshorastrab.addActionListener(accion);
        this.jMenuItemconsrecord.addActionListener(accion);
        this.jMenuItemconsutilidad.addActionListener(accion);
        this.jMenuItemferiado.addActionListener(accion);
        this.jMenuItemgestclientes.addActionListener(accion);
        this.jMenuItemgestentrevistas.addActionListener(accion);
        this.jMenuItemgestproyectos.addActionListener(accion);
        this.jMenuItemregfaltas.addActionListener(accion);
        this.jMenuItemregnomina.addActionListener(accion);
        this.jMenuItemAsigCand.addActionListener(accion);
        this.jMenuItemgestcandidato.addActionListener(accion);
        this.jMenuItemIngreso.addActionListener(accion);
       
            
        
        
        
    }
            

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelimag;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAsigCand;
    private javax.swing.JMenuItem jMenuItemIngreso;
    private javax.swing.JMenuItem jMenuItemconscandidatos;
    private javax.swing.JMenuItem jMenuItemconsentrevistas;
    private javax.swing.JMenuItem jMenuItemconsfaltas;
    private javax.swing.JMenuItem jMenuItemconshorastrab;
    private javax.swing.JMenuItem jMenuItemconsrecord;
    private javax.swing.JMenuItem jMenuItemconsutilidad;
    private javax.swing.JMenuItem jMenuItemferiado;
    private javax.swing.JMenuItem jMenuItemgestcandidato;
    private javax.swing.JMenuItem jMenuItemgestclientes;
    private javax.swing.JMenuItem jMenuItemgestentrevistas;
    private javax.swing.JMenuItem jMenuItemgestproyectos;
    private javax.swing.JMenuItem jMenuItemregfaltas;
    private javax.swing.JMenuItem jMenuItemregnomina;
    private javax.swing.JMenu jMenucandidato;
    private javax.swing.JMenu jMenuconsultas;
    private javax.swing.JMenu jMenuempleados;
    private javax.swing.JMenu jMenuferiado;
    private javax.swing.JMenu jMenuproyectos;
    // End of variables declaration//GEN-END:variables
}
